### ISSUE TITLE
Pre-trained model tokenizer in the README.md

### ISSUE THREAD

**Issue by dkelesch** [enjakokalj/TransSHAP#1]
Pre-trained model tokenizer in the README.md (pretrained_model = "./models/en_balanced_bertbase-g512-epochs3/") does not seem to be valid anymore. It requires an updated model on Hugging Face to be used instead when I run on Google Colab

**Comment by sb1992** [comment]
Hey how did you resolve this issue?

**Comment by dkelesch** [comment]
Yes, I have. I have changed the model they used.
Best,
Deniz K.


Shraey Bhatia ***@***.***>, 24 Ağu 2021 Sal, 10:50 tarihinde
şunu yazdı:

**Comment by sb1992** [comment]
So could you point me to a model that i could use? That would be much appreciated

**Comment by dkelesch** [comment]
I was essentially plugging a private model, but any BERT model for
sentiment analysis on huggingface should do for the initial step.


Shraey Bhatia ***@***.***>, 24 Ağu 2021 Sal, 11:16 tarihinde
şunu yazdı:

**Comment by menxp** [comment]
When you plugged another model, did you still use the raw config.json file or use config file of your model ?
