### ISSUE TITLE
Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index', 'flax_model.msgpack'] found in directory ./models/en_balanced_bertbase-g512-epochs3/ or `from_tf` and `from_flax` set to False.

### ISSUE THREAD

**Issue by renhao1998** [enjakokalj/TransSHAP#3]
Hello,
when i run the code , it report this error, i want to know if you offer this model?
and how can i explain my fine-turing model? can you off an example?
thank you so much!

**Comment by Sonbul001** [comment]
How did you solve this problem ?
